### PR TITLE
added placeholder audio for sunsfan and slacks

### PR DESCRIPTION
**Pull request by VicFrank**
Plays placeholder audio anytime for each sunsfan/slacks dialog line

### CODE REVIEW

**Comment by RobinKa** [comment]
plz no sir

**Comment by VicFrank** [comment]
Made it toggleable. Also put in the dev panel location lookup. If you want to find the location of somewhere on the map, just move a unit there (spawn with -createhero if you have to) and the dev panel will tell you its current position.

**Comment by RobinKa** [comment]
Note: This PR adds new folders in the content directory for the sounds which causes the tooling to break when switching between branches (I had the same issue when I added particles and created the particles folder in content). Once we get this into master (after tediously unbreaking everything a bunch of times: delete game/content dir of addon in dota, delete files, `git checkout .`, `git pull upstream master`, `npm install`, ctrl+shift+b, play dota vidya game, merge this PR into master to break everyone else and have them do these steps) it should be fine though.

**Comment by RobinKa** [comment]
We have some real sounds now so I don't t hink this is needed a nymore, but a separate PR for the dev menu stuff would be nice.

**Pull request closed without merging**
