### PR TITLE
Add current chapter label

### LINKED ISSUE #525: Show current chapter
GENERAL: Showing the current chapter/section the player is in at all times might help give them context so the player isn't lost.

------
People don't mind that the tutorial is long because it's divided into skippable chapters. However, it's hard to determine which chapter you're currently in.

Adding a panel that shows the current chapter will assist with that. The panel can either be constantly shown, or shown briefly in a flashy way when transitioning to a new chapter.

### PR DESCRIPTION
**Pull request by RobinKa**
Uses the existing section started event. (Assumes that the sections start with the chapter name, eg. Chapter1_Bla to get the chapter nr for localization)

Fixes #525 

image

### CODE REVIEW

**Comment by Shushishtok** [comment]
@RobinKa Do you think it's visible enough? I know people are effectively blind when it comes to things like that.
Maybe a bigger size and a background?

**Comment by RobinKa** [comment]
I can add an animation for when it changes. Can make it bigger too.

**Comment by RobinKa** [comment]
image
Bigger now and added a glow animation whenever a new section starts.

**Comment by Shushishtok** [comment]
That's so sexy!

**Review by Shushishtok — APPROVED** [review]

**Pull request merged**
