### PR TITLE
Section/ch3 polish merge

### PR DESCRIPTION
**Pull request by Wouterz90**

### CODE REVIEW

**Comment by Wouterz90** [comment]
- [ ] Getting the riki thing done (Moving to a visible point, saying something, and moving away)
- [ ] Fixing the highlighting

**Comment by RobinKa** [comment]
I got this error after stacking the first time

```ts
Script Runtime Error: scripts\vscripts\Dialog.ts:58: attempt to index local 'speaker' (a nil value)
stack traceback:
	[C]: in function '__index'
	scripts\vscripts\Dialog.ts:58: in function 'play'
	scripts\vscripts\Dialog.ts:110: in function 'playCommon'
	scripts\vscripts\Dialog.ts:132: in function 'playText'
	scripts\vscripts\TutorialGraph/Steps.ts:669: in function 'start'
	scripts\vscripts\TutorialGraph/Core.ts:134: in function 'complete'
	scripts\vscripts\TutorialGraph/Steps.ts:509: in function 'start'
	scripts\vscripts\TutorialGraph/Core.ts:134: in function 'startStep'
	scripts\vscripts\TutorialGraph/Core.ts:139: in function 'start'
	scripts\vscripts\TutorialGraph/Core.ts:134: in function 'complete'
	scripts\vscripts\TutorialGraph/Steps.ts:509: in function 'start'
	scripts\vscripts\TutorialGraph/Core.ts:132: in function 'dialogEndedCallback'
	scripts\vscripts\Dialog.ts:85: in function <scripts\vscripts\Dialog.lua:67>
```

- Should use a numeric goal for tracking how often you stacked and how often you need to stack
- If you want, you could already add audio dialog since it's all in now (basically change `textDialog` to `audioDialog` and the audio and text parameters are then identical, also make sure to remove the last parameter for the seconds since those otherwise get added onto the time of the audio)

**Comment by Wouterz90** [comment]
Ah yes, I faked that, I'll add it to the list.

> Should use a numeric goal for tracking how often you stacked and how often you need to stack

Will change

**Review by RobinKa — CHANGES_REQUESTED** [review]
Noticed some big issues here eg. the localization got changed incorrectly and some stuff with the logic. I'm working on the changes myself atm and will commit them soon.

// I made the dialog fit now and removed some of the wrong changes. Still some issues for example you can kill the last neutral camp before the quest for it comes up but most important things are fixed now and displayed correctly. Also formatted everything.

**Review by RobinKa — APPROVED** [review]

**Pull request merged**
